name: new_version
description: Check if your user has the most recent version of your Flutter app.
version: 0.3.8
homepage: https://github.com/timtraversy/new_version

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  http: ^1.6.0
  html: ^0.15.6
  url_launcher: ^6.3.2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
